#!/usr/bin/env bash
# Generated by ptoas-workspace-manager; source this file.
export PTO_SOURCE_DIR=/home/toni/work/pypto3_sync_more/PTOAS-insertsync-r1
export PTO_BUILD_DIR=/home/toni/work/pypto3_sync_more/insertsync-builds/PTOAS-insertsync-r1
export LLVM_BUILD_DIR=/home/toni/work/llvm19/llvm-project/build-shared
export PYTHON_BIN=/home/toni/work/pypto3_sync_more/PTOAS-insertsync-r1/.venv/bin/python
source "$PTO_SOURCE_DIR/.venv/bin/activate"
export PTOAS_WORKSPACE_METADATA="$PTO_SOURCE_DIR/.ptoas-workspace.json"
