# ----------------------------------------------------------------------------
# Copyright (c) 2025 Huawei Technologies Co., Ltd.
# This program is free software, you can redistribute it and/or modify it under the terms and conditions of
# CANN Open Software License Agreement Version 2.0 (the "License").
# Please refer to the License for details. You may not use this file except in compliance with the License.
# THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
# INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
# See LICENSE in the root of the software repository for the full text of the License.
# ----------------------------------------------------------------------------
#### CPACK to package run #####

function(pack_built_in)
  #### built-in package ####
  message(STATUS "CMAKE_INSTALL_PREFIX = ${CMAKE_INSTALL_PREFIX}")
  message(STATUS "System processor: ${CMAKE_SYSTEM_PROCESSOR}")

  string(FIND "${ASCEND_COMPUTE_UNIT}" ";" SEMICOLON_INDEX)
  if (SEMICOLON_INDEX GREATER -1)
      math(EXPR SUBSTRING_LENGTH "${SEMICOLON_INDEX}")
      string(SUBSTRING "${ASCEND_COMPUTE_UNIT}" 0 "${SUBSTRING_LENGTH}" compute_unit)
  else()
      set(compute_unit "${ASCEND_COMPUTE_UNIT}")
  endif()

  message(STATUS "current compute_unit is: ${compute_unit}")

  set(PTOAS_ROOT_DIR "${CMAKE_SOURCE_DIR}")

  if(NOT DEFINED PTOAS_WHEEL_FILE OR NOT EXISTS "${PTOAS_WHEEL_FILE}")
      message(FATAL_ERROR "PTOAS_WHEEL_FILE must point to the repaired PTOAS wheel")
  endif()
  if(IS_DIRECTORY "${PTOAS_WHEEL_FILE}")
      message(FATAL_ERROR "PTOAS_WHEEL_FILE must be a file: ${PTOAS_WHEEL_FILE}")
  endif()

  set(SCRIPTS_FILES
      ${CANN_CMAKE_DIR}/scripts/install/check_version_required.awk
      ${CANN_CMAKE_DIR}/scripts/install/common_func.inc
      ${CANN_CMAKE_DIR}/scripts/install/common_interface.sh
      ${CANN_CMAKE_DIR}/scripts/install/common_interface.csh
      ${CANN_CMAKE_DIR}/scripts/install/common_interface.fish
      ${CANN_CMAKE_DIR}/scripts/install/version_compatiable.inc
      ${PTOAS_ROOT_DIR}/scripts/package/pto_as/scripts/cleanup.sh
      ${PTOAS_ROOT_DIR}/scripts/package/pto_as/scripts/help.info
      ${PTOAS_ROOT_DIR}/scripts/package/pto_as/scripts/install.sh
      ${PTOAS_ROOT_DIR}/scripts/package/pto_as/scripts/pto_common.sh
      ${PTOAS_ROOT_DIR}/scripts/package/pto_as/scripts/pto_custom_install.sh
      ${PTOAS_ROOT_DIR}/scripts/package/pto_as/scripts/pto_custom_uninstall.sh
      ${PTOAS_ROOT_DIR}/scripts/package/pto_as/scripts/pto_install.sh
      ${PTOAS_ROOT_DIR}/scripts/package/pto_as/scripts/pto_uninstall.sh
      ${PTOAS_ROOT_DIR}/scripts/package/pto_as/scripts/uninstall.sh
      ${PTOAS_ROOT_DIR}/scripts/package/pto_as/scripts/ver_check.sh
  )

  install(FILES ${SCRIPTS_FILES}
      DESTINATION share/info/pto_as/script
      ${INSTALL_OPTIONAL}
      COMPONENT pto_as
      PERMISSIONS
      OWNER_READ OWNER_WRITE OWNER_EXECUTE
      GROUP_READ GROUP_EXECUTE
      WORLD_READ WORLD_EXECUTE
  )

  set(COMMON_FILES
      ${CANN_CMAKE_DIR}/scripts/install/install_common_parser.sh
      ${CANN_CMAKE_DIR}/scripts/install/common_func_v2.inc
      ${CANN_CMAKE_DIR}/scripts/install/common_installer.inc
      ${CANN_CMAKE_DIR}/scripts/install/script_operator.inc
      ${CANN_CMAKE_DIR}/scripts/install/version_cfg.inc
  )

  set(PACKAGE_FILES
      ${COMMON_FILES}
      ${CANN_CMAKE_DIR}/scripts/install/multi_version.inc
  )

  install(FILES ${CMAKE_BINARY_DIR}/version.pto_as.info
      DESTINATION share/info/pto_as
      RENAME version.info
      ${INSTALL_OPTIONAL}
      COMPONENT pto_as
  )
  # scene.info is generated by scripts/package/pto_as/pto_as.xml.

  install(FILES ${PACKAGE_FILES}
      DESTINATION share/info/pto_as/script
      ${INSTALL_OPTIONAL}
      COMPONENT pto_as
  )

  install(DIRECTORY ${PTOAS_ROOT_DIR}/include/
      DESTINATION ${CMAKE_SYSTEM_PROCESSOR}-linux/include
      ${INSTALL_OPTIONAL}
      COMPONENT pto_as
      FILE_PERMISSIONS OWNER_READ OWNER_WRITE GROUP_READ GROUP_EXECUTE
      PATTERN CMakeLists.txt EXCLUDE
      PATTERN pto-c EXCLUDE
      PATTERN PTO EXCLUDE
  )

  if(CMAKE_BUILD_TYPE)
      string(TOLOWER "${CMAKE_BUILD_TYPE}" PTOAS_TARGETS_CONFIG_SUFFIX)
  else()
      set(PTOAS_TARGETS_CONFIG_SUFFIX "noconfig")
  endif()

  # build.sh installs the exported targets before CPack stages this component.
  # Reuse that public install tree instead of CMakeFiles/Export, whose internal
  # layout is not materialized consistently across CMake versions.
  install(FILES
      ${CMAKE_INSTALL_PREFIX}/${PTOAS_CMAKE_INSTALL_DIR}/PTOASTargets.cmake
      ${CMAKE_INSTALL_PREFIX}/${PTOAS_CMAKE_INSTALL_DIR}/PTOASTargets-${PTOAS_TARGETS_CONFIG_SUFFIX}.cmake
      ${CMAKE_INSTALL_PREFIX}/${PTOAS_CMAKE_INSTALL_DIR}/PTOASConfig.cmake
      DESTINATION ${PTOAS_CMAKE_INSTALL_DIR}
      ${INSTALL_OPTIONAL}
      COMPONENT pto_as
  )

  install(FILES "${PTOAS_WHEEL_FILE}"
      DESTINATION tools/ptoas/wheels
      ${INSTALL_OPTIONAL}
      COMPONENT pto_as
  )

  install(FILES ${PTOAS_ROOT_DIR}/scripts/package/pto_as/bin/ptoas
      DESTINATION tools/ptoas/bin
      ${INSTALL_OPTIONAL}
      COMPONENT pto_as
      PERMISSIONS OWNER_READ OWNER_EXECUTE GROUP_READ GROUP_EXECUTE
  )

  # For rpm/deb packages, prefix each RUN_DEPENDENCIES_LIST entry's version with
  # ">=" so convert_dependencies_to_package_formats produces well-formed Requires/
  # Depends ("pkg >= 9.1") instead of "pkg 9.1" (which RPM splits into a phantom
  # "9.1" standalone dependency). This must NOT touch version.info: that file is
  # generated from CANN_VERSION_*_RUN_DEPS (a separate list), not from
  # RUN_DEPENDENCIES_LIST, so the run package's version check still sees the plain
  # version "9.0" expected by the install.sh version_valid logic.
  if(PACKAGE_TYPE STREQUAL "rpm" OR PACKAGE_TYPE STREQUAL "deb"
     OR PACKAGE_TYPE STREQUAL "deb,rpm" OR PACKAGE_TYPE STREQUAL "all")
      set(_patched_deps "")
      foreach(_dep_entry ${RUN_DEPENDENCIES_LIST})
          # _dep_entry is "pkg version" (space-separated); prefix version with >=.
          string(REGEX REPLACE "^([^ ]+) +(.*)" "\\1 >= \\2" _patched "${_dep_entry}")
          list(APPEND _patched_deps "${_patched}")
      endforeach()
      set(RUN_DEPENDENCIES_LIST "${_patched_deps}")
  endif()

  # cann-cmake sets CPACK_PACKAGE_NAME to "cann-${component}" = "cann-pto_as".
  # With CPACK_RPM_COMPONENT_INSTALL/CPACK_DEB_COMPONENT_INSTALL ON, CPack appends
  # the component name ("pto_as") to the package name AND to the file name,
  # producing the duplicated "cann-pto_as-pto_as". Set the per-component package
  # name and file name explicitly before set_cann_cpack_config so the cann-cmake
  # include(CPack) picks them up. The <COMPONENT> part must be UPPER-CASE per CMake
  # docs (CPackDeb only honors the upper-case form; CPackRPM accepts both).
  # We use the historical "cann-pto-as" (hyphen) for the Name field to stay
  # consistent with the makeself run package filename.
  set(CPACK_RPM_PTO_AS_PACKAGE_NAME "cann-pto-as")
  set(CPACK_DEBIAN_PTO_AS_PACKAGE_NAME "cann-pto-as")
  string(TOLOWER "${CMAKE_SYSTEM_NAME}" _sys_name_lower)
  set(_file_name_base "cann-pto-as_${CANN_VERSION_pto_as_VERSION}_${_sys_name_lower}-${CMAKE_SYSTEM_PROCESSOR}")
  set(CPACK_RPM_PTO_AS_FILE_NAME "${_file_name_base}.rpm")
  set(CPACK_DEBIAN_PTO_AS_FILE_NAME "${_file_name_base}.deb")
  # DEB control "Package" field also honors the non-component variable when the
  # generator builds a single component; set it to the same value to be sure.
  set(CPACK_DEBIAN_PACKAGE_NAME "cann-pto-as")

  set_cann_cpack_config(pto_as
      COMPUTE_UNIT "${compute_unit}"
      SHARE_INFO_NAME pto_as
      OUTPUT "${CMAKE_SOURCE_DIR}/build_out"
      PACKAGE_TYPE "${PACKAGE_TYPE}"
  )
endfunction()
